{% set name = "poppy-ergo-jr" %}
{% set version = "2.0.0" %}
package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  path: ../

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
    - pypot >3
    - hampy

  run:
    - python
    - pypot >3
    - opencv3
    - hampy

test:

  # Python imports
  imports:
    - poppy_ergo_jr

about:
  home: https://github.com/poppy-project/poppy-ergo-jr
  summary: 'Poppy Ergo Jr Software Library'
  license: GNU GENERAL PUBLIC LICENSE Version 3
  license_family: GPL3
  summary: Poppy Ergo Jr Software Library
  doc_url: 'https://docs.poppy-project.org/'
  dev_url: 'http://github.com/poppy-project/poppy-ergo-jr'
